import '@angular/platform-browser'
import '@angular/platform-browser-dynamic'
import '@angular/core'
import '@angular/common'
import '@ionic-native/core'
import '@ionic-native/splash-screen'
import '@ionic-native/status-bar'
import 'ionic-angular'

import 'reactivedb'
import 'teambition-sdk'
import 'snapper-consumer'
